### ISSUE TITLE
issues with `order`, `fdp` output

### ISSUE THREAD

**Issue by pkimes** [lihualei71/adaptMT#1]
Thanks for turning this into a package!
I'm interested in testing out the AdaPT method and tried running the `estrogen` example in the vignette. The code runs without any errors, but the `res$order` and `res$fdp` outputs are twice the length of the number of p-values in the original data set (10,000 vs. 5,000). This doesn't seem correct. Do you know what might be going on?

Also, it looks like both `res$order` and `res$fdp` might be backwards/reversed. The documentation says that `res$fdp` is comprised of values where the "i-th entry records the FDPhat when i-th hypothesis is rejected", but the values appear to be mostly decreasing (just looking at `plot(res$fdp[1:5000])`). Same thing when I check the original p-values against the indices in `res$order`. Maybe the order needs to be reversed?

Just to make sure I know how to use the output from the method, can you help point out the easiest way to determine which tests should be rejected at a certain FDR threshold? Should I use `res$nrejs` for the corresponding alpha and reject the tests with indices in, e.g. `res$order[1:res$nrejs[which(res$alphas == 0.05)]]`? Or should I be using the `res$fdp` values instead? I also noticed you calculate the local FDR for plots - should I be using lfdrs from `compute_lfdr_mix()`?

Thanks! Looking forward to testing this out.

**Comment by lihualei71** [comment]
Thanks for pointing out this issue! I fixed this bug. Please download the latest version of this package. I add a test in tests/ that will guarantee the absence of this issue in future development.

To be clear, `res$order` is the order of reveal, rather than the order of rejection. As described in our paper, AdaPT reveals p-values gradually and those which are revealed are the ones accepted, rather than rejected. Similarly, `res$fdp` gives the FDP estimate when the hypothesis is rejected and thus it should be decreasing because it is expected to go down when more and more p-values are unmasked.

To obtain the set of rejections, I add a new output `rejs` in `adapt` in the latest version, which is a list of length `length(alphas)` and each element gives the set of indices of rejected hypotheses. The most simple alternative method to get it for a particular alpha is to call `which(pvals <= res$s[, alphaind])` where `alphaind` is the index of alpha in `alphas`. The test in tests/ guarantees the consistency between `res$rejs` and this approach. On the other hand, It would be more complicated to recover `res$rejs` from `res$order` because the latter gives the order of revealed p-values, rather than rejected p-values. The complement set of revealed p-values include both rejected p-values and those are above 1 - thresholds. 

Finally, the function `compute_lfdr_mix` is only an internal function in the package because the user should not bother with local FDR computation.

**Comment by pkimes** [comment]
@lihualei71, thanks for adding the `res$rejs` output and clarifying `res$order`.

I'm still a little confused about `res$fdp`. 
> Similarly, `res$fdp` gives the FDP estimate when the hypothesis is rejected and thus it should be decreasing because it is expected to go down when more and more p-values are unmasked.

Do you mean `res$fdp` gives the FDP estimate when the i-th **revealed** hypothesis is rejected? Currently, the function documentation just says "a vector of values in [0, 1]. i-th entry records the FDPhat when i-th hypothesis is rejected." This sounds like `res$fdp[1]` would be the FDP when the 1st hypothesis is rejected, and `res$fdp[5000]` would be the FDP when all hypotheses are rejected. 

One last question. If I want q-value estimates (as described in 4.4.3.), is it fair to set alpha to a fine grid (e.g. `c(seq(0.001, 0.15, 0.001), seq(0.16, 1, .01))`) and set the q-value of test `i` to the largest alpha such that test `i` is in `res$rejs`, or should this be using the `res$fdp` FDPhat values  instead?

**Comment by lihualei71** [comment]
Regarding the first question: sorry for the confusion. What I really mean is: `res$fdp[i]` gives the FDP estimate when the `res$order[i]`-th hypothesis is revealed (not rejected). Here is a toy example: given five p-values 0.001, 0.0001, 0.47, 0.7, 0.05 and suppose AdaPT simply look at min{p_i, 1 - p_i} and reveal the p-values in a descending order. Then `res$order = c(3, 4, 5, 1, 2)` and `res$fdp = c(2/3, 1/3, 1/2, 1/2, 1)`. For instance, the first entry 2/3 is obtained by (1+A)/R, where A = 1, R = 3 because only one p-value (0.7) is above 1-s while all other three are below s.

Regarding the second question: thanks for pointing this out. The procedure you described is definitely correct, though it is not recommended because the output `res$s` has `length(alphas)` columns and this will increases the size of this object significantly. As you mentioned, `res$fdp` gives a faster yet more precise q-values. In fact, given alpha and any i, `res$order[i:n]` will be rejected if `res$fdp[1:(i-1)]` contains a value <= alpha. Thus, the q-value for `res$order[i]` is `min res$fdp[1:(i-1)]`.

Thanks for your valuable questions. I realize that `res$fdp` is confusing and not very useful. So I remove it and add `qvals`, the q-values, into `adapt`. With `qvals` one can determine the set of rejections with level alpha by collecting all those hypotheses with q-values <= alpha. I added a test into tests/ to guarantee the consistency between these two outputs.

**Comment by pkimes** [comment]
@lihualei71, thanks again for the quick response and changes to the package! As a user, I agree that the `qvals` output is probably more useful. Thanks for adding this!

**Comment by pkimes** [comment]
@lihualei71 - one more question. If I'm interested in the complete `res$qvals` output, does it make sense to set `alphas=` to a single small value (e.g. < 1/M)? 

Since setting multiple alphas doesn't change the q-value estimates and setting `min(alphas)` too large causes the code to terminate early (e.g. setting `alphas = 1`), this seemed like the best thing to do. Can you just confirm if this makes sense? 

Thanks for the help!

**Comment by lihualei71** [comment]
Yes, you are absolutely correct. Simply set alpha = 0. 

We will add in a future version an input `s_return` in `adapt` to indicate whether the thresholds should be returned. Currently the package is under review on CRAN so I add this new feature a few days later.

**Comment by pkimes** [comment]
Sounds great - thanks!
